stages:
  - Testing

Testing:
  image: cypress/browsers:node18.12.0-chrome106-ff106
  stage: Testing
  script:
    # install dependencies
    - cd cypress
    
    - npm ci
    # start the server in the background
    - npm start &
    # run Cypress tests
    - npx cypress run --browser chrome